### ISSUE TITLE
Title for references

### ISSUE THREAD

**Issue by valentynbez** [universvm/academic-pandoc-templates#2]
Hello! 
Thanks for tutorial, everything works great, almost :)
Currently the title for references doesn't render, do you know what might be the issue? 
![image](https://github.com/universvm/obsidian-pandoc-templates/assets/61702053/9fe4b618-7998-41a3-8562-95b212f1cf31)

Cheers!

**Comment by DrLeucine** [comment]
Hi @valentynbez , 

Could you share the command you are using to generate this?

I believe you just need to add this line to your pandoc command:

```
-M reference-section-title=References
```

I updated the blogpost (it was placed in a legacy section). Let me know if this works

**Comment by valentynbez** [comment]
Perfect, thanks a lot :)
