### ISSUE TITLE
LaTex Error: pgfpages.sty not found

### ISSUE THREAD

**Issue by BravishkaSkytano** [universvm/academic-pandoc-templates#3]
![image](https://github.com/universvm/obsidian-pandoc-templates/assets/65601594/eff0eaae-2d64-4dbf-ba3f-cc9fc76d9dac)

I am using Obsidian on my Chromebook. I have Pandoc and PDFLatex installed.

**Comment by DrLeucine** [comment]
I think you need to install the package. No clue how chromebooks work, do you have a terminal where you can paste this:

> tlmgr install pgf

**Comment by BravishkaSkytano** [comment]
(Newer) Chromebooks have Linux beta on them, so we do have a terminal and we can install some Linux apps.

> I think you need to install the package. No clue how chromebooks work, do you have a terminal where you can paste this:
> 
> > tlmgr install pgf

That command doesn't work, I might need to install some stuff first. I'll probably get to it a little later in the week and get back to you.

**Comment by ibehnam** [comment]
> (Newer) Chromebooks have Linux beta on them, so we do have a terminal and we can install some Linux apps.
> 
> > I think you need to install the package. No clue how chromebooks work, do you have a terminal where you can paste this:
> > > tlmgr install pgf
> 
> That command doesn't work, I might need to install some stuff first. I'll probably get to it a little later in the week and get back to you.

Were you able to fix this problem? I'm trying to use the templates available in the plugin but I get this error:

```
Command: pandoc -f markdown --resource-
path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research"--resource-
path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research"--lua-
filter="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research/.obsidian/plugins/obsidian-enhancing-
export/lua/pdf.lua" --resource-
path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research/.obsidian/plugins/obsidian-enhancing-
export/textemplate" --template="neurips.tex" -s -0
"/Users/behnam/Downloads/Paper.pdf"-t pdf--pdf-engine=pdflatex
"/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research/Paper.md", Error:Error: Command failed:
pandoc-f markdown --resource-
path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research"--resource-
path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research"--lua-
filter="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research/.obsidian/plugins/obsidian-enhancing-
export/lua/pdf.lua" --resource-
path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research/.obsidian/plugins/obsidian-enhancing-
export/textemplate" --template="neurips.tex" -s -o
"/Users/behnam/Downloads/Paper.pdf"-t pdf--pdf-engine=pdflatex
"/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research/Paper.md" Error producing PDF.! LaTeX Error:
File 'environ.sty' not found. Type X to quit or < RETURN> to proceed, or enter
new name. (Default extension: sty) Enter file name: ! Emergency stop. <read *>
1.62 \newcommand
```

It seems like a `*.sty` file is not found.

**Comment by DrLeucine** [comment]
> > (Newer) Chromebooks have Linux beta on them, so we do have a terminal and we can install some Linux apps.
> > > I think you need to install the package. No clue how chromebooks work, do you have a terminal where you can paste this:
> > > > tlmgr install pgf
> > 
> > 
> > That command doesn't work, I might need to install some stuff first. I'll probably get to it a little later in the week and get back to you.
> 
> Were you able to fix this problem? I'm trying to use the templates available in the plugin but I get this error:
> 
> ```
> Command: pandoc -f markdown --resource-
> path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
> 5/Research/Obsidian/Research"--resource-
> path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
> 5/Research/Obsidian/Research"--lua-
> filter="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
> 5/Research/Obsidian/Research/.obsidian/plugins/obsidian-enhancing-
> export/lua/pdf.lua" --resource-
> path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
> 5/Research/Obsidian/Research/.obsidian/plugins/obsidian-enhancing-
> export/textemplate" --template="neurips.tex" -s -0
> "/Users/behnam/Downloads/Paper.pdf"-t pdf--pdf-engine=pdflatex
> "/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
> 5/Research/Obsidian/Research/Paper.md", Error:Error: Command failed:
> pandoc-f markdown --resource-
> path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
> 5/Research/Obsidian/Research"--resource-
> path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
> 5/Research/Obsidian/Research"--lua-
> filter="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
> 5/Research/Obsidian/Research/.obsidian/plugins/obsidian-enhancing-
> export/lua/pdf.lua" --resource-
> path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
> 5/Research/Obsidian/Research/.obsidian/plugins/obsidian-enhancing-
> export/textemplate" --template="neurips.tex" -s -o
> "/Users/behnam/Downloads/Paper.pdf"-t pdf--pdf-engine=pdflatex
> "/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
> 5/Research/Obsidian/Research/Paper.md" Error producing PDF.! LaTeX Error:
> File 'environ.sty' not found. Type X to quit or < RETURN> to proceed, or enter
> new name. (Default extension: sty) Enter file name: ! Emergency stop. <read *>
> 1.62 \newcommand
> ```
> 
> It seems like a `*.sty` file is not found.

Hi, I believe your problem is related to the plugin. 

Can you check that these are your Environment variables (cmd + , > export settings)?
```
HOME="${HOME}"
PATH="/usr/local/bin:/Library/TeX/texbin:${PATH}"
TEXINPUTS="${pluginDir}/textemplate/:"
```

**Comment by ibehnam** [comment]
@universvm Thanks for following up. Yes, mine looks the same:

```
HOME="${HOME}"
PATH="/opt/homebrew/bin:/usr/local/bin:/Library/TeX/texbin:${PATH}"
TEXINPUTS="${pluginDir}/textemplate/:"
```

**Comment by DrLeucine** [comment]
@ibehnam 

Could you try running:

```
sudo tlmgr install environ
```

**Comment by ibehnam** [comment]
> @ibehnam
> 
> Could you try running:
> 
> ```
> sudo tlmgr install environ
> ```

I tried it and restarted Obsidian as well. But I still get an error:

```
Command: pandoc -f markdown --resource-
path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research"--resource-
path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research" --lua-
filter="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research/.obsidian/plugins/obsidian-enhancing-
export/lua/pdf.lua" --resource-
path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research/.obsidian/plugins/obsidian-enhancing-
export/textemplate" --template="neurips.tex" -s -o
"/Users/behnam/Downloads/Paper.pdf"-t pdf--pdf-engine=pdflatex
"/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research/Paper.md", Error:Error: Command failed:
pandoc-f markdown --resource-
path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research"--resource-
path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research"--lua-
filter="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research/.obsidian/plugins/obsidian-enhancing-
export/lua/pdf.lua" --resource-
path="/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research/.obsidian/plugins/obsidian-enhancing-
export/textemplate" --template="neurips.tex" -s -o
"/Users/behnam/Downloads/Paper.pdf"-t pdf--pdf-engine=pdflatex
"/Users/behnam/Library/CloudStorage/OneDrive-Personal/Year
5/Research/Obsidian/Research/Paper.md" Error producing PDF.! LaTeX Error:
File 'nicefrac.sty' not found. Type X to quit or < RETURN> to proceed, or enter
new name. (Default extension: sty) Enter file name: ! Emergency stop. <read *>
1.33 lusepackage
```

**Comment by DrLeucine** [comment]
@ibehnam I think we're moving forward, now it's `nicefrac.sty`. Can you try either:

```
sudo tlmgr install units
```

or

```
sudo tlmgr install nicefrac
```

**Comment by BravishkaSkytano** [comment]
I wasn't able to fix this for myself (not enough free time) so I use a different plugin to convert it to a document for me to open and format and export in another application.

**Comment by DrLeucine** [comment]
Closing this issue as the author did not have time to try the debugging steps. If you have the same problems please feel free to reopen the issue.
