### ISSUE TITLE
Neurips template is not working

### ISSUE THREAD

**Issue by brunoleej** [universvm/academic-pandoc-templates#6]
Hello, I’m trying to use the NeurIPS templates, but I have some issues.

1. The guideline indicates that I should put the YAML template at the top of my article. I tried to follow the steps as shown in the figure below, but it is not working at all.

![Screenshot 2024-09-05 at 2 47 09 AM](https://github.com/user-attachments/assets/d565b96d-8e3a-48de-b47c-dcde5a2f8655)

The result is like this:
[Test.pdf](https://github.com/user-attachments/files/16874837/Test.pdf)

How can I fix this issue?

Here's my "Extra arguments" for now:
--csl https://raw.githubusercontent.com/csthiago/zotero-citation-styles/master/ieee.csl  --pdf-engine=/Library/TeX/texbin/pdflatex --filter pandoc-crossref --number-sections --citeproc -M reference-section-title=References

**Comment by DrLeucine** [comment]
Could you attach your md file? I suspect there is a space/newline as the first character which is interfering with the identification of the YAML part

**Comment by brunoleej** [comment]
Thank you for your help. Here's my markdown file.
[Test.md](https://github.com/user-attachments/files/16874943/Test.md)

**Comment by DrLeucine** [comment]
Yup. This is your problem (at the top of your file)

```
---

---
---

```

Try the file I've attached [Test.md](https://github.com/user-attachments/files/16874951/Test.md)

I wonder why this happened though, could you let me know if this happens if you create a new file from scratch? Maybe it's something to do with your obsidian setup

**Comment by brunoleej** [comment]
As you suggested, removing the spaces solved the problem. However, the spaces are not visible on my Obsidian screen. In such cases, should I directly use properties to edit YAML format in Obsidian? I created the YAML using text style.

**Comment by DrLeucine** [comment]
https://github.com/user-attachments/assets/43bd33cf-42cd-41e0-b72d-e727325fccc2

I'm not too sure, this is what happens when I copy and paste the YAML above. It's automatically parsed as property. It does not seem to be doing this in your setup?

**Comment by brunoleej** [comment]
First of all, thank you very much for providing a solution! When I tried the method, the results were as shown in the video below.

Uploading Screen Recording 2024-09-05 at 3.07.57 AM.mov…

**Comment by brunoleej** [comment]
First of all, thank you very much for providing a solution! When I tried the method, the results were as shown in the video below.


https://github.com/user-attachments/assets/3918062c-3f3c-449f-882c-1a48f080c66a

**Comment by brunoleej** [comment]
I created a new Markdown file and pasted the content you mentioned, and it solved the problem! However, it seems that the author information is not being updated. Could you also provide a solution for this issue?


https://github.com/user-attachments/assets/ffd4a7e8-11bd-4840-9811-e422820acb63

**Comment by DrLeucine** [comment]
@brunoleej sorry I just saw this. Could you try to edit in source mode?

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
