### ISSUE TITLE
NeurIPS template obsolete

### ISSUE THREAD

**Issue by andreapisa9** [universvm/academic-pandoc-templates#7]
Already reported in the [obsidian-enhancing-export](https://github.com/mokeyish/obsidian-enhancing-export) repo, see [# 250](https://github.com/mokeyish/obsidian-enhancing-export/issues/250).

Is it possible to add custom templates?

**Comment by DrLeucine** [comment]
Ciao Andrea,

Thanks for reporting it, let me have a look
